import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "../components/ui/card";
import { Button } from "../components/ui/button";
import { useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  Globe,
  TrendingUp,
  Award,
  Shield,
  BarChart3,
  Map,
} from "lucide-react";

export function AboutPage() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      {/* Header with Back Button */}
      <div className="border-b">
        <div className="container mx-auto px-4 py-4">
          <Button
            variant="ghost"
            onClick={() => navigate("/")}
            className="mb-4"
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Viewer
          </Button>
        </div>
      </div>

      {/* Main Content */}
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        {/* Hero Section */}
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold mb-4 bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
            Global Developer Statistics
          </h1>
          <p className="text-xl text-muted-foreground">
            See how much code developers around the world write themselves
            versus what's generated by AI, all in real time and fully anonymous.
          </p>
        </div>

        {/* Introduction Card */}
        <Card className="mb-8">
          <CardContent className="pt-6">
            <p className="text-lg leading-relaxed">
              WhoDare gives you a unique perspective on coding habits across
              countries, languages, and experience levels.
            </p>
          </CardContent>
        </Card>

        {/* How It Works Section */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="text-2xl flex items-center gap-2">
              <BarChart3 className="h-6 w-6" />
              How It Works
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground leading-relaxed">
              Whenever you push code to your repository, WhoDare automatically
              updates your daily coding stats to a centralized database. Only
              percentage metrics are shared — your actual code never leaves your
              system. This integration is designed solely for statistical
              insights, keeping individual coding sessions private and secure.
            </p>
          </CardContent>
        </Card>

        {/* What You Get Section */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="text-2xl flex items-center gap-2">
              <Globe className="h-6 w-6" />
              What You Get
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-6">
              <div className="flex gap-4">
                <div className="flex-shrink-0">
                  <Map className="h-6 w-6 text-blue-600" />
                </div>
                <div>
                  <h3 className="font-semibold mb-2">
                    Live World Map & Rankings
                  </h3>
                  <p className="text-muted-foreground">
                    Explore which countries write the most human-written code
                    and where AI assistance is most commonly used.
                  </p>
                </div>
              </div>

              <div className="flex gap-4">
                <div className="flex-shrink-0">
                  <BarChart3 className="h-6 w-6 text-green-600" />
                </div>
                <div>
                  <h3 className="font-semibold mb-2">Language Breakdown</h3>
                  <p className="text-muted-foreground">
                    Compare coding patterns across languages like JavaScript,
                    Python, Rust, and more. See which language communities rely
                    on AI more or less.
                  </p>
                </div>
              </div>

              <div className="flex gap-4">
                <div className="flex-shrink-0">
                  <Award className="h-6 w-6 text-yellow-600" />
                </div>
                <div>
                  <h3 className="font-semibold mb-2">
                    Weekly Top 100 "Pure Human" Coders
                  </h3>
                  <p className="text-muted-foreground">
                    Celebrate the developers with the highest proportion of
                    human-written code using anonymous nicknames.
                  </p>
                </div>
              </div>

              <div className="flex gap-4">
                <div className="flex-shrink-0">
                  <TrendingUp className="h-6 w-6 text-purple-600" />
                </div>
                <div>
                  <h3 className="font-semibold mb-2">Daily Updating Charts</h3>
                  <p className="text-muted-foreground">
                    Watch trends evolve with easy-to-read visualizations that
                    refresh automatically.
                  </p>
                </div>
              </div>

              <div className="flex gap-4">
                <div className="flex-shrink-0">
                  <Globe className="h-6 w-6 text-red-600" />
                </div>
                <div>
                  <h3 className="font-semibold mb-2">Global Trends Insights</h3>
                  <p className="text-muted-foreground">
                    Identify patterns in coding workflows, AI adoption, and
                    collaboration across different regions and developer
                    communities.
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Privacy & Security Section */}
        <Card className="mb-8 border-green-200 dark:border-green-800">
          <CardHeader>
            <CardTitle className="text-2xl flex items-center gap-2">
              <Shield className="h-6 w-6 text-green-600" />
              Privacy & Security
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <p className="text-muted-foreground leading-relaxed">
                Your real code always stays private. Only the calculated
                percentages are sent to the shared database when you push your
                code.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                You can disable the feature anytime in settings. Being open
                source, the entire process is transparent, secure, and
                verifiable.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Call to Action */}
        <Card className="bg-gradient-to-r from-blue-600 to-purple-600 text-white border-0">
          <CardContent className="pt-6 pb-6 text-center">
            <h2 className="text-2xl font-bold mb-4">
              Join the largest open view of "Who really writes code in 2025"
            </h2>
            <p className="text-lg mb-6 opacity-90">
              See how human developers and AI collaborate globally. Track
              trends, compare languages, and gain insights into the evolution of
              coding patterns, all while keeping your code completely safe.
            </p>
            <Button
              variant="secondary"
              size="lg"
              onClick={() => navigate("/")}
              className="font-semibold"
            >
              Get Started Now
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
